### PR TITLE
Added profile in hacker-profile.json file

### PR DESCRIPTION
**Pull request by SattyamSamania**
**Description**

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Comment by ayushsoni1010** [comment]
Hey @SattyamSamania 👋
Good to see you here!

Can you make a new branch and later create a PR, if a merge happens PR, then rebased commits will be added and seems like your commit is unverified.
It's better to take a pull from the `master` branch.

Let me know if you need any help.
Can't wait to see your profile on the `HEKORS hacker profiles` website

Keep contributing :)

**Comment by SattyamSamania** [comment]
> Hey @SattyamSamania 👋 Good to see you here!
> 
> Can you make a new branch and later create a PR, if a merge happens PR, then rebased commits will be added and seems like your commit is unverified. It's better to take a pull from the `master` branch.
> 
> Let me know if you need any help. Can't wait to see your profile on the `HEKORS hacker profiles` website
> 
> Keep contributing :)

Sure. Can you please suggest some solution of this unverified commit. It's showing me error when I add new GPG key.

**Comment by ayushsoni1010** [comment]
This cause is occurring due to your local git config, make sure you should configured it with the right email

Alright!
Let's have a voice call on the Hekors discord community server in the #general voice channel

**Comment by SattyamSamania** [comment]
> This cause is occurring due to your local git config, make sure you should configured it with the right email
> 
> Alright! Let's have a voice call on the Hekors discord community server in the #general voice channel

Sure.

**Pull request merged**
